version: '3'
services:
  ci4-asn:
    build:
      context: ./
    ports:
      - "80:80"
    volumes:
      - ./asn:/var/www/html/asn
    restart: always
    container_name: ci4-asn-apache-php

  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=dbapp
      - MYSQL_USER=nonodev96
      - MYSQL_PASSWORD=secret
      # Descomentar si hay problemas para incializar la BD de pruebas
      # https://github.com/docker-library/mariadb/issues/160#issuecomment-528393445
#     - MYSQL_INIT_SKIP_TZINFO=1
    ports:
      - 3306:3306
    restart: always
    container_name: ci4-asn-database

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
      - PMA_PASSWORD=secret
    restart: always
    container_name: ci4-asn-phpmyadmin
